# Generated by Django 5.0.1 on 2024-02-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='type_of_car',
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
